apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: employees
spec:
  containers:
    - name: webapp
      image: <ecr-repo-url>/assignment2-webapp:latest
      ports:
        - containerPort: 80
