apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: webapp
          image: <ecr-repo-url>/assignment2-webapp:latest
          ports:
            - containerPort: 80
